.PHONY: subdirs

subdirs:
	$(MAKE) -C src/minitel
	$(MAKE) -C src/racine

install:
	$(MAKE) -C src/minitel install
	$(MAKE) -C src/racine install

clean:
	$(MAKE) -C src/minitel clean
	$(MAKE) -C src/racine clean
